# Generated by Django 5.2.9 on 2025-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_team_org_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_mandate_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mandate ID from payment provider (GoCardless)",
                max_length=255,
            ),
        ),
    ]
