# Generated by Django

from django.db import migrations


def grandfather_oidc_email_confirmed(apps, schema_editor):
    """Set email_confirmed=True for users who already have OIDC with verified emails."""
    UserProfile = apps.get_model("core", "UserProfile")
    UserOIDC = apps.get_model("core", "UserOIDC")

    # Find all OIDC records with verified emails and update their profiles
    verified_oidc_user_ids = list(
        UserOIDC.objects.filter(email_verified=True).values_list("user_id", flat=True)
    )

    if verified_oidc_user_ids:
        UserProfile.objects.filter(
            user_id__in=verified_oidc_user_ids,
            email_confirmed=False,
        ).update(email_confirmed=True)


def reverse_grandfather(apps, schema_editor):
    """No-op reverse: we cannot know which users were previously unconfirmed."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_emailconfirmationtoken"),
    ]

    operations = [
        migrations.RunPython(
            grandfather_oidc_email_confirmed,
            reverse_code=reverse_grandfather,
        ),
    ]
