# Generated by Django 5.2.14 on 2026-06-28 15:17

from django.db import migrations, models


def copy_email_tokens_to_user_profiles(apps, schema_editor):
    """Copy email confirmation tokens from EmailConfirmationToken to UserProfile."""
    EmailConfirmationToken = apps.get_model("core", "EmailConfirmationToken")
    UserProfile = apps.get_model("core", "UserProfile")

    # Copy token data to user profiles
    for token in EmailConfirmationToken.objects.select_related("user__profile"):
        try:
            profile = token.user.profile
            profile.email_confirmation_token = token.token
            profile.email_confirmation_token_expires = token.expires_at
            profile.save(
                update_fields=[
                    "email_confirmation_token",
                    "email_confirmation_token_expires",
                ]
            )
        except Exception as e:
            print(f"Warning: Could not copy token for user {token.user_id}: {e}")
            continue


def reverse_copy_email_tokens(apps, schema_editor):
    """Reverse operation - clear token fields in user profiles."""
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.filter(email_confirmation_token__isnull=False).update(
        email_confirmation_token=None, email_confirmation_token_expires=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_grandfather_oidc_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmation_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmation_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            copy_email_tokens_to_user_profiles, reverse_copy_email_tokens
        ),
    ]
