# Generated by Django 5.2.14 on 2026-06-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_copy_email_tokens_to_user_profiles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailConfirmationToken",
        ),
    ]
