# Generated by Django 5.2.15 on 2026-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_delete_emailconfirmationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingoverride",
            name="amount",
            field=models.IntegerField(
                help_text="Price inclusive of VAT in pence. Auto-computed from amount_ex_vat and VAT_RATE on save (e.g. 2400 = £24.00 at 20% VAT)."
            ),
        ),
        migrations.AlterField(
            model_name="pricingoverride",
            name="amount_ex_vat",
            field=models.IntegerField(
                help_text="Price exclusive of VAT in pence (e.g. 2000 = £20.00). This is the canonical field; the inc-VAT amount is derived from it."
            ),
        ),
    ]
