# Generated by Django 5.2.15 on 2026-07-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_pricing_override_vat_derived_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="Promotion applied at checkout that reduced the charged amount, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.promotion",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="effective_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Effective tier after any tier-override promotion at checkout. May differ from `tier` when a promotion upgraded the subscriber.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_checkout_amount_ex_vat",
            field=models.IntegerField(
                default=0,
                help_text="Ex-VAT pence actually charged at the most recent checkout (includes any applied promotion). Used by the payment webhook to create an accurate Payment record.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_checkout_applied_promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="Promotion applied at the most recent checkout, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_checkouts",
                to="core.promotion",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_checkout_effective_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Effective tier after any tier-override promotion at the most recent checkout. May differ from account_tier when a promotion upgrades the subscriber.",
                max_length=30,
            ),
        ),
    ]
