# Generated by Django 5.2.15 on 2026-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_payment_promotion_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="monthly",
                help_text="Billing cycle for this payment (monthly or annual)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_checkout_billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="monthly",
                help_text="Billing cycle selected at the most recent checkout (monthly or annual). Used by the payment webhook to create an accurate Payment record with the correct interval and amount.",
                max_length=10,
            ),
        ),
    ]
