# Generated by Django 5.2.16 on 2026-08-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_billing_cycle_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Provider event id (e.g. GoCardless 'EV...' id).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="'{resource_type}.{action}' for GoCardless events.",
                        max_length=64,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the event was first processed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed webhook event",
                "verbose_name_plural": "Processed webhook events",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="core_webhoo_event_i_b5925d_idx"
                    )
                ],
            },
        ),
    ]
