# Generated by Django 5.2.8 on 2025-11-30 19:56

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0032_alter_surveyquestioncondition_action_team_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="require_passphrase_for_patient_data",
            field=models.BooleanField(
                default=True,
                help_text="Require SSO users to set a passphrase when survey collects patient data (recommended)",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="enc_answers",
            field=models.BinaryField(
                blank=True,
                help_text="Encrypted survey answers (AES-256-GCM) for patient data surveys",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RecoveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_code",
                    models.CharField(
                        editable=False,
                        help_text="Human-readable request code for reference",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Identity Verification"),
                            (
                                "verification_in_progress",
                                "Identity Verification In Progress",
                            ),
                            ("awaiting_primary", "Awaiting Primary Authorization"),
                            ("awaiting_secondary", "Awaiting Secondary Authorization"),
                            ("in_time_delay", "In Time Delay Period"),
                            ("ready_for_execution", "Ready for Execution"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_verification",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When both approvals completed", null=True
                    ),
                ),
                (
                    "time_delay_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Recovery can execute after this time",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_delay_hours",
                    models.PositiveIntegerField(
                        default=48,
                        help_text="Hours to wait after approval before execution (24h org, 48h individual)",
                    ),
                ),
                ("primary_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "primary_reason",
                    models.TextField(
                        blank=True, help_text="Primary approver's verification notes"
                    ),
                ),
                ("secondary_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "secondary_reason",
                    models.TextField(
                        blank=True, help_text="Secondary approver's verification notes"
                    ),
                ),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "custodian_component_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether platform custodian component was used for recovery",
                    ),
                ),
                (
                    "vault_recovery_path",
                    models.CharField(
                        blank=True,
                        help_text="Vault path to escrowed recovery key",
                        max_length=500,
                    ),
                ),
                (
                    "user_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User details captured at request time (email, account age, etc.)",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_cancellations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_primary_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondary_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recovery_secondary_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_requests",
                        to="surveys.survey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryAuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of event (e.g., request_submitted, primary_approval, recovery_executed)",
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(help_text="user, admin, or system", max_length=20),
                ),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                (
                    "actor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("actor_user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "entry_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of entry for tamper detection",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of previous entry in chain",
                        max_length=64,
                    ),
                ),
                ("forwarded_to_siem", models.BooleanField(default=False)),
                ("forwarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recovery_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="surveys.recoveryrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery Audit Entry",
                "verbose_name_plural": "Recovery Audit Entries",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("photo_id", "Photo ID"),
                            ("video_call", "Video Verification Call"),
                            ("security_questions", "Security Questions"),
                            ("employment_verification", "Employment Verification"),
                            ("sso_reauth", "SSO Re-authentication"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted storage path for uploaded documents",
                        max_length=500,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of document (e.g., UK Driving Licence)",
                        max_length=100,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on verification"
                    ),
                ),
                (
                    "video_call_scheduled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "video_call_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "video_recording_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to encrypted video recording (if enabled)",
                        max_length=500,
                    ),
                ),
                (
                    "questions_asked",
                    models.JSONField(
                        blank=True, default=list, help_text="List of questions asked"
                    ),
                ),
                (
                    "correct_answers",
                    models.IntegerField(
                        blank=True, help_text="Number of correct answers", null=True
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(
                        blank=True, help_text="Total questions asked", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_delete_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Documents auto-deleted 30 days after request completion",
                        null=True,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recovery_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verifications",
                        to="surveys.recoveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recoveryrequest",
            index=models.Index(
                fields=["status", "-submitted_at"], name="surveys_rec_status_1f3e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryrequest",
            index=models.Index(
                fields=["user", "-submitted_at"], name="surveys_rec_user_id_5e60a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryrequest",
            index=models.Index(
                fields=["survey", "-submitted_at"],
                name="surveys_rec_survey__7ce26f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryrequest",
            index=models.Index(
                fields=["time_delay_until"], name="surveys_rec_time_de_5d07f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryrequest",
            index=models.Index(
                fields=["request_code"], name="surveys_rec_request_beec85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryauditentry",
            index=models.Index(
                fields=["recovery_request", "-timestamp"],
                name="surveys_rec_recover_cdbde1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryauditentry",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="surveys_rec_event_t_0abdb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryauditentry",
            index=models.Index(
                fields=["severity", "-timestamp"], name="surveys_rec_severit_d4aa70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryauditentry",
            index=models.Index(
                fields=["actor_id"], name="surveys_rec_actor_i_1c8331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoveryauditentry",
            index=models.Index(
                fields=["forwarded_to_siem"], name="surveys_rec_forward_82302e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(
                fields=["recovery_request", "verification_type"],
                name="surveys_ide_recover_d08f66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(fields=["status"], name="surveys_ide_status_a36b59_idx"),
        ),
        migrations.AddIndex(
            model_name="identityverification",
            index=models.Index(
                fields=["auto_delete_at"], name="surveys_ide_auto_de_d90b61_idx"
            ),
        ),
    ]
