# Generated by Django 5.2.8 on 2025-12-01 21:22

from django.db import migrations, models
import django.db.models.deletion

import checktick_app.surveys.models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0033_add_whole_response_encryption"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=checktick_app.surveys.models.question_image_upload_path
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label/alt text for the image",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="surveys.surveyquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
