# Generated by Django 5.2.12 on 2026-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0044_initialize_platform_key_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveymembership",
            name="can_change_survey_style",
            field=models.BooleanField(
                default=False,
                help_text="Allow this member to edit the survey's visual style (colours, fonts, branding). Only effective on paid tiers; free-tier users are always denied.",
            ),
        ),
    ]
