# Generated by Django 5.2.12 on 2026-03-27 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0045_add_can_change_survey_style"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("per_seat", "Per Seat"),
                    ("flat_rate", "Flat Rate"),
                    ("invoice", "Invoice (Manual)"),
                    ("free", "Free (Internal/Trial)"),
                ],
                default="per_seat",
                help_text="How this organisation is billed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform admin who created this organisation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checktick-light", "CheckTick Light"),
                    ("checktick-dark", "CheckTick Dark"),
                ],
                default="",
                help_text="Default theme for organisation (empty = use platform default)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this organisation is active"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the organisation (set during checkout completion)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="setup_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the organisation owner completed setup",
                null=True,
            ),
        ),
    ]
