# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0048_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("update", "Update"),
                    ("create", "Create"),
                    ("invite", "Invite"),
                    ("key_recovery", "Key Recovery"),
                    ("login_success", "Successful Login"),
                    ("login_failed", "Failed Login Attempt"),
                    ("logout", "Logout"),
                    ("account_locked", "Account Locked"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_verified", "2FA Verification Success"),
                    ("2fa_failed", "2FA Verification Failed"),
                    ("backup_codes_generated", "Backup Codes Generated"),
                    ("backup_code_used", "Backup Code Used"),
                    ("password_changed", "Password Changed"),
                    ("password_reset", "Password Reset Requested"),
                    ("email_changed", "Email Address Changed"),
                    ("user_created", "User Account Created"),
                    ("user_deactivated", "User Account Deactivated"),
                    ("user_deleted", "User Account Deleted"),
                    ("data_exported", "Data Exported"),
                    ("promotion_activated", "Promotion Activated"),
                    ("promotion_ending_soon", "Promotion Ending Soon"),
                    ("promotion_expired", "Promotion Expired"),
                    ("promotion_reconciled", "Promotion Reconciled"),
                ],
                max_length=30,
            ),
        ),
    ]
