# Generated by Django 5.2.15 on 2026-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0049_add_user_deleted_audit_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("annual", "Annual")],
                default="monthly",
                help_text="Billing cycle for this organisation (monthly or annual). Annual applies the configured ANNUAL_DISCOUNT_PERCENT.",
                max_length=10,
            ),
        ),
    ]
