# Generated by Django 5.2.17 on 2026-08-30 12:01

from django.db import migrations, models

from checktick_app.surveys.migrations._backfill_helpers import (
    backfill_hidden_by_default,
    rename_skip_to_hide,
    reverse_backfill_hidden_by_default,
    reverse_rename_hide_to_skip,
)


class Migration(migrations.Migration):

    dependencies = [
        (
            "surveys",
            "0051_dataset_team_dataset_surveys_dat_team_id_617829_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="hidden_by_default",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, the question is hidden unless a SHOW condition "
                    "reveals it. When False (default), it is shown unless a HIDE "
                    "condition hides it."
                ),
            ),
        ),
        migrations.RunPython(
            backfill_hidden_by_default,
            reverse_backfill_hidden_by_default,
        ),
        migrations.RunPython(
            rename_skip_to_hide,
            reverse_rename_hide_to_skip,
        ),
        migrations.AlterField(
            model_name="surveyquestioncondition",
            name="action",
            field=models.CharField(
                choices=[
                    ("show", "Show when condition met (hidden by default)"),
                    ("jump_to", "Skip ahead to question"),
                    ("hide", "Hide when condition met"),
                    ("end_survey", "End survey"),
                ],
                default="jump_to",
                max_length=32,
            ),
        ),
    ]
