# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0052_hidden_by_default_and_rename_skip_to_hide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestioncondition",
            name="action",
            field=models.CharField(
                choices=[
                    ("show", "Show when condition met (hidden by default)"),
                    ("jump_to", "Skip ahead to question"),
                    ("hide", "Hide when condition met"),
                    ("end_survey", "End survey"),
                ],
                default="jump_to",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestioncondition",
            name="target_group",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Section target for jump_to. Resolved to the first question "
                    "in the section at config-build time. Only used when action "
                    "is jump_to."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_conditions",
                to="surveys.questiongroup",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="surveyquestioncondition",
            name="surveyquestioncondition_single_target",
        ),
        migrations.AddConstraint(
            model_name="surveyquestioncondition",
            constraint=models.CheckConstraint(
                condition=(
                    Q(target_question__isnull=False)
                    | Q(target_group__isnull=False)
                    | Q(
                        action="end_survey",
                        target_question__isnull=True,
                        target_group__isnull=True,
                    )
                ),
                name="surveyquestioncondition_single_target",
            ),
        ),
    ]
