# Generated by Django 5.2.17 on 2026-08-31 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0053_readd_target_group_for_section_jumps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="audience_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True once the creator has explicitly confirmed the respondent audience",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="encryption_opt_out_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the creator declared the encryption opt-out for this survey",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="encryption_opt_out_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the encryption opt-out declaration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encryption_opt_out_surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="encryption_opt_out_declaration_version",
            field=models.CharField(
                blank=True,
                help_text="Version of the opt-out declaration text acknowledged by the creator",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="respondent_audience",
            field=models.CharField(
                choices=[
                    ("staff", "Staff / colleagues"),
                    ("patient", "Patients"),
                    ("public", "Public / respondents"),
                ],
                default="staff",
                help_text="Declared audience for this survey (drives at-rest encryption of responses)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("remove", "Remove"),
                    ("update", "Update"),
                    ("create", "Create"),
                    ("invite", "Invite"),
                    ("key_recovery", "Key Recovery"),
                    ("login_success", "Successful Login"),
                    ("login_failed", "Failed Login Attempt"),
                    ("logout", "Logout"),
                    ("account_locked", "Account Locked"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_verified", "2FA Verification Success"),
                    ("2fa_failed", "2FA Verification Failed"),
                    ("backup_codes_generated", "Backup Codes Generated"),
                    ("backup_code_used", "Backup Code Used"),
                    ("password_changed", "Password Changed"),
                    ("password_reset", "Password Reset Requested"),
                    ("email_changed", "Email Address Changed"),
                    ("user_created", "User Account Created"),
                    ("user_deactivated", "User Account Deactivated"),
                    ("user_deleted", "User Account Deleted"),
                    ("data_exported", "Data Exported"),
                    ("promotion_activated", "Promotion Activated"),
                    ("promotion_ending_soon", "Promotion Ending Soon"),
                    ("promotion_expired", "Promotion Expired"),
                    ("promotion_reconciled", "Promotion Reconciled"),
                    ("encryption_opt_out_declared", "Encryption Opt-out Declared"),
                    ("encryption_opt_out_revoked", "Encryption Opt-out Revoked"),
                    (
                        "responses_encrypted_backfill",
                        "Responses Encrypted (Backfill Migration)",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
