# Generated by Django 5.2.17 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0055_grandfather_encryption_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="submission_public_key",
            field=models.BinaryField(
                blank=True,
                help_text="Raw X25519 public key used to encrypt responses at submission time",
                null=True,
            ),
        ),
    ]
