# Generated by Django 5.2.17 on 2026-08-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0056_survey_submission_public_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="enc_submission_private_key",
            field=models.BinaryField(
                blank=True,
                help_text="Submission private key encrypted with the survey KEK (migrated surveys only)",
                null=True,
            ),
        ),
    ]
