# Generated by Django 5.2.17 on 2026-09-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0061_sectionmenu_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionmenu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sectionmenuitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
